# Generated by Django 5.2.3 on 2025-06-28 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='website_url',
            field=models.URLField(blank=True, help_text='Link către site-uri adiacente evenimentului', null=True),
        ),
    ]
